version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.9.0
    - 3.9.1
  - dependency-name: swagger-ui
    versions:
    - 3.43.0
    - 3.44.0
    - 3.44.1
    - 3.45.0
    - 3.45.1
    - 3.46.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: react
    versions:
    - 17.0.1
